-- ─────────────────────────────────────────────────────────────────────────────
-- kip-forms D1 schema — inquiries table
-- Run via: wrangler d1 execute kip-inquiries --file schema.sql
-- (or via Cloudflare Dashboard → D1 → kip-inquiries → Console)
-- ─────────────────────────────────────────────────────────────────────────────

CREATE TABLE IF NOT EXISTS inquiries (
  id            TEXT PRIMARY KEY,        -- UUID generated by the Worker
  form_id       TEXT NOT NULL,           -- partner | subscribe | contact | story | shops | i500 | checkout | press
  name          TEXT NOT NULL,
  email         TEXT NOT NULL,
  organisation  TEXT,                    -- nullable; some forms don't ask
  message       TEXT,                    -- nullable in schema, validated NOT-empty by the Worker
  subject       TEXT,                    -- nullable; press-form uses it
  deadline      TEXT,                    -- nullable; press-form uses it
  submitted_at  TEXT NOT NULL,           -- ISO 8601 from the Worker
  user_agent    TEXT                     -- truncated UA, ≤300 chars
);

-- Index by form_id so the founder can query "all partner inquiries this week"
-- without a full table scan.
CREATE INDEX IF NOT EXISTS idx_inquiries_form_id     ON inquiries(form_id);
CREATE INDEX IF NOT EXISTS idx_inquiries_submitted_at ON inquiries(submitted_at);

-- Optional: a status column + admin notes column for later workflow. Add when
-- the inquiry pipeline outgrows email triage. Schema stays additive — no
-- ALTER TABLE drops, ever, per §10 v4.10 federation-is-a-schema-extension rule.
--
-- ALTER TABLE inquiries ADD COLUMN status TEXT DEFAULT 'new';
-- ALTER TABLE inquiries ADD COLUMN admin_notes TEXT;
